"""
DRISHTI-X — Report Generation Service
Generates structured screening reports as JSON (and optionally HTML/PDF).

Every report is clearly labeled:
  AI-ASSISTED SCREENING — NOT A FINAL MEDICAL DIAGNOSIS

Reports include:
  - Patient information
  - Image quality
  - DR grade + confidence
  - Lesion findings
  - Grad-CAM reference
  - Evidence summary
  - Risk level + referral priority
  - Assurance decision
  - Doctor review (if completed)
  - Audit trail reference
  - Disclaimer
"""
import os
import json
from datetime import datetime, timezone
from typing import Optional, Dict, Any
from pathlib import Path


DISCLAIMER = (
    "AI-ASSISTED SCREENING — NOT A FINAL MEDICAL DIAGNOSIS. "
    "This report is generated by an AI screening prototype and requires "
    "ophthalmologist review before any clinical decision is made. "
    "This system is NOT clinically approved or CE/FDA/CDSCO certified."
)

DR_GRADE_LABELS = {
    0: "No DR",
    1: "Mild Non-Proliferative DR (NPDR)",
    2: "Moderate NPDR",
    3: "Severe NPDR",
    4: "Proliferative DR (PDR)",
}


def generate_report(
    screening,
    patient,
    fundus_image,
    prediction,
    doctor_review,
    generated_by_user_id: Optional[str] = None,
    output_dir: str = "reports",
) -> Dict[str, Any]:
    """
    Generate a structured screening report dict.
    Saves as JSON. HTML/PDF generation can be added here.

    Returns the report dict.
    """
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now(timezone.utc).isoformat()

    # ── Quality summary ──────────────────────────────────────
    quality_summary = None
    if fundus_image:
        quality_summary = {
            "quality_score":       fundus_image.quality_score,
            "focus_score":         fundus_image.focus_score,
            "illumination_score":  fundus_image.illumination_score,
            "fov_score":           fundus_image.fov_score,
            "is_gradable":         fundus_image.is_gradable,
            "feedback":            fundus_image.quality_feedback,
        }

    # ── Prediction summary ───────────────────────────────────
    ai_summary = None
    if prediction:
        grade = prediction.predicted_grade
        ai_summary = {
            "predicted_grade":   grade,
            "grade_label":       DR_GRADE_LABELS.get(grade, "Unknown") if grade is not None else "NOT AVAILABLE",
            "confidence":        prediction.confidence,
            "probabilities":     prediction.probabilities,
            "is_referable":      prediction.is_referable,
            "model_name":        prediction.model_name,
            "model_version":     prediction.model_version,
            "model_status":      prediction.model_status,
            "is_demo":           prediction.is_demo,
            "weights_hash":      prediction.weights_hash,
            "gradcam_available": prediction.gradcam_path is not None,
            "gradcam_path":      prediction.gradcam_path,
            "lesion_summary":    prediction.lesion_summary,
            "concordance_score": prediction.concordance_score,
            "concordance_level": prediction.concordance_level,
            "mismatch_detected": prediction.mismatch_detected,
            "mismatch_details":  prediction.mismatch_details,
        }

    # ── Doctor review summary ────────────────────────────────
    doctor_summary = None
    if doctor_review:
        doc_grade = doctor_review.doctor_grade
        doctor_summary = {
            "doctor_grade":       doc_grade,
            "doctor_grade_label": DR_GRADE_LABELS.get(doc_grade, "Unknown") if doc_grade is not None else None,
            "doctor_is_referable": doctor_review.doctor_is_referable,
            "doctor_notes":       doctor_review.doctor_notes,
            "ai_grade_accepted":  doctor_review.ai_grade_accepted,
            "ai_grade_modified":  doctor_review.ai_grade_modified,
            "reviewed_at":        doctor_review.reviewed_at.isoformat() if doctor_review.reviewed_at else None,
        }

    # ── Assurance + referral ─────────────────────────────────
    assurance_summary = {
        "decision":          screening.assurance_decision.value if screening.assurance_decision else None,
        "reasons":           screening.assurance_reasons,
        "referral_priority": screening.referral_priority.value if screening.referral_priority else None,
        "referral_score":    screening.referral_score,
        "is_referable":      screening.is_referable,
    }

    # ── Recommendation ───────────────────────────────────────
    recommendation = _generate_recommendation(
        assurance_summary["decision"],
        assurance_summary["referral_priority"],
        ai_summary,
        doctor_summary,
    )

    # ── Final report ─────────────────────────────────────────
    report = {
        "report_id":          f"RPT-{screening.id}",
        "generated_at":       timestamp,
        "generated_by":       str(generated_by_user_id) if generated_by_user_id else "SYSTEM",
        "disclaimer":         DISCLAIMER,
        "screening": {
            "id":             str(screening.id),
            "patient_id":     str(screening.patient_id),
            "eye_side":       screening.eye_side,
            "created_at":     screening.created_at.isoformat() if screening.created_at else None,
            "analyzed_at":    screening.analyzed_at.isoformat() if screening.analyzed_at else None,
            "status":         screening.status.value if screening.status else None,
        },
        "patient": {
            "patient_code":   patient.patient_code if patient else "UNKNOWN",
            "age":            patient.age if patient else None,
            "gender":         patient.gender.value if (patient and patient.gender) else None,
            "district":       patient.district if patient else None,
            "state":          patient.state if patient else None,
        },
        "image_quality":      quality_summary,
        "ai_prediction":      ai_summary,
        "doctor_review":      doctor_summary,
        "assurance":          assurance_summary,
        "recommendation":     recommendation,
    }

    # Save to disk
    report_path = os.path.join(output_dir, f"report_{screening.id}.json")
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2, default=str)

    return report


def _generate_recommendation(
    assurance_decision: Optional[str],
    referral_priority: Optional[str],
    ai_summary: Optional[Dict],
    doctor_summary: Optional[Dict],
) -> Dict[str, Any]:
    """Generate a structured recommendation based on assurance + grade."""

    # Use doctor grade if available, fall back to AI grade
    final_grade = None
    if doctor_summary and doctor_summary.get("doctor_grade") is not None:
        final_grade = doctor_summary["doctor_grade"]
        grade_source = "DOCTOR"
    elif ai_summary and ai_summary.get("predicted_grade") is not None:
        final_grade = ai_summary["predicted_grade"]
        grade_source = "AI_MODEL"
    else:
        grade_source = "UNAVAILABLE"

    # Clinical pathway
    if assurance_decision == "RECAPTURE_REQUIRED":
        pathway = "RECAPTURE_REQUIRED"
        action = "Recapture fundus image with improved focus and illumination before proceeding."
    elif final_grade in (3, 4) or referral_priority in ("CRITICAL", "HIGH"):
        pathway = "IMMEDIATE_REFERRAL"
        action = "Immediate telemedicine referral to District Eye Specialist Hospital."
    elif final_grade == 2 or referral_priority == "MEDIUM":
        pathway = "REFERRAL_WITHIN_ONE_MONTH"
        action = "Refer to ophthalmologist within one month. Monitor for progression."
    elif assurance_decision == "HUMAN_REVIEW_REQUIRED":
        pathway = "HUMAN_REVIEW_REQUIRED"
        action = "Ophthalmologist review required before any clinical decision."
    elif final_grade in (0, 1):
        pathway = "ROUTINE_SCREENING"
        action = "Annual routine re-screening in 12 months."
    else:
        pathway = "UNDETERMINED"
        action = "Model prediction unavailable. Ophthalmologist review required."

    return {
        "clinical_pathway":  pathway,
        "action":            action,
        "final_grade":       final_grade,
        "grade_source":      grade_source,
        "referral_priority": referral_priority,
    }
